# -*- coding: utf-8 -*-
"""1º Exercicio Gioliano/Algoritmos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOtwI5GtCilZhRkVX4N0nPy3Fzhss28T
"""

print('Olá mundo!')

# prompt: fazer um sigma de i = 1 e n = 3

print('Olá mundo!')

def sigma(n):
  soma = 0
  for i in range(1, n + 1):
    soma += i
  return soma

resultado = sigma(3)
print(resultado)  # Output: 6

n1 = float(input('Digite um número:'))
n2 = float(input('Digite um outro número:'))
soma = n1 + n2
print (f'A soma dos dois numeros é {soma}')

n = int(input('Digite um número: '))

if n % 2 == 0:
    print(f'O número {n} é par')
else:
     print(f'O número {n} é impar')

n1 = int(input('Digite um número: '))
n2 = int(input('Digite um outro número: '))
operacao = input('Digite a operação desejada (+, -, *, /):')

if operacao == '+':
    soma = n1 + n2
    print(f'A soma dos dois números é {soma}.')
elif operacao == '-':
     subtracao = n1 - n2
     print(f'A subtração dos dois números é {subtracao}.')
elif operacao == '*':
      multiplicacao = n1 * n2
      print (f'A multiplicaçao dos dois números é {multiplicacao}')
elif operacao == '/':
      divisao = n1 / n2
      print(f'A divisão dos dois números é {divisao}')

n1 = float(input('Digite a sua primeira nota: '))
n2 = float(input('Digite a sua segunda nota: '))
n3 = float(input('Digite a sua terceira nota: '))
media = (n1 + n2 + n3) / 3
print(f'Sua média foi de {media :.1f}')

celsius = int(input("Digite a temperatura em Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print(f"A temperatura em Fahrenheit é: {fahrenheit:.0f}°")

numero = int(input("Digite um número para calcular o fatorial: "))
fatorial = 1
if numero < 0:
    print("Fatorial não definido para números negativos.")
elif numero == 0:
    print("O fatorial de 0 é 1.")
else:
    for i in range(1, numero + 1):
        fatorial *= i
    print(f"O fatorial de {numero} é {fatorial}")

contador = 1

while contador <= 100:
  if contador % 2 != 0:
    print(contador)
  contador += 1

numero = int(input("Digite um número inteiro: "))
if numero <= 1:
    primo = False
else:
    primo = True
    for i in range(2, int(numero ** 0.5) + 1):
        if numero % i == 0:
            primo = False
            break

if primo:
    print(f"O número {numero} é primo.")
else:
    print(f"O número {numero} não é primo.")

texto = input("Digite uma string: ")
texto_invertido = texto[::-1]
print("A string invertida é:", texto_invertido)

numero = int(input("Digite um número para ver a tabuada: "))

print(f"Tabuada de {numero}:")
for i in range(1, 11):
    resultado = numero * i
    print(f"{numero} x {i} = {resultado}")

numeros = [1, 2, 3, 4, 5]
soma = 0

for numero in numeros:
    soma += numero

print("A soma dos elementos da lista é:", soma)

numeros_str = input("Digite uma lista de números separados por espaço: ")
numeros_lista = [int(x) for x in numeros_str.split()]

if numeros_lista:
    maior_numero = max(numeros_lista)
    print("O maior número da lista é:", maior_numero)
else:
    print("A lista está vazia.")

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for numero in numeros:
  if numero % 2 == 0:
    print(numero)

contador = 10

while contador >= 0:
  print(contador)
  contador -= 1

a, b = 0, 1
count = 0

while count < 10:
    print(a, end=" ")
    a, b = b, a + b
    count += 1

import random

resultado = random.choice(['cara', 'coroa'])
print(f'O resultado do lançamento da moeda é: {resultado}')

palavra = input("Digite uma palavra: ")
palavra = palavra.lower().replace(" ", "")

if palavra == palavra[::-1]:
  print("A palavra é um palíndromo.")
else:
  print("A palavra não é um palíndromo.")

import random

numero_secreto = random.randint(1, 100)
tentativas = 0

print("Bem-vindo ao jogo de adivinhação!")
print("Eu escolhi um número entre 1 e 100. Tente adivinhar!")

while True:
  tentativa = int(input("Digite seu palpite: "))
  tentativas += 1

  if tentativa == numero_secreto:
    print(f"Parabéns! Você acertou em {tentativas} tentativas.")
    break
  elif tentativa < numero_secreto:
    print("Tente um número maior.")
  else:
    print("Tente um número menor.")